version: 2
jobs:
  build-and-test-python37: &build-and-test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip --quiet
            pip install .
            pip install .[dev]
          # pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            pytest -vv src/gros/tests

  build-and-test-python38: 
    <<: *build-and-test-template
    docker:
      - image: circleci/python:3.8

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test-python37
      - build-and-test-python38
